# Server
server.port=8081

# Spring Application
spring.application.name=AiAgent-core

# Spring AI OpenAI
spring.ai.openai.api-key=${ALIQIANWEN_PLUS_API_KEY:default-empty}
spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode
spring.ai.openai.chat.options.model=qwen-plus

# MCP SSE Client
spring.ai.mcp.client.name=AiAgent-core
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.request-timeout=30s
spring.ai.mcp.client.sse.connections.stock-mcp.url=http://localhost:8082
spring.ai.mcp.client.sse.connections.stock-mcp.sse-endpoint=/sse

# Logging
logging.level.root=info
logging.level.com.zhn.aiagent=debug
