# Server
server.port=8082

# Spring Application
spring.application.name=AiAgent-mcp

# MCP SSE Server
spring.ai.mcp.server.name=AiAgent-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=SSE
spring.ai.mcp.server.sse-endpoint=/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/message

# Logging
logging.level.root=info
logging.level.com.zhn.aiagent=debug
